name: Build and Publish
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@modyo'
    - name: Install dependencies with yarn
      # if your project use more than one private registry you cad add it like this:
      # run: |
      #   echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
      #   echo "//npm.fontawesome.com/:_authToken=$FORTAWESOME_TOKEN" >> .npmrc
      #   yarn
      # if not do this:
      run: |
        cd modyo-widgets-investments-accounts
        yarn
      env:
        # And add the additional registry token here:
        # FORTAWESOME_TOKEN: ${{secrets.FORTAWESOME_TOKEN}}
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Package
      run: | 
        cd modyo-widgets-investments-accounts
        yarn build
    - name: Push to Modyo Site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MODYO_ACCOUNT_URL: ${{secrets.BASE_URL}}
        MODYO_VERSION: ${{secrets.VERSION}}
        MODYO_TOKEN: ${{secrets.TOKEN}}
        MODYO_SITE_ID: ${{secrets.SITE_ID}}
        MODYO_WIDGET_NAME: ${{secrets.WIDGET_NAME}}
      run: |  
        echo "GITHUB_TOKEN: $GITHUB_TOKEN"
        echo "MODYO_ACCOUNT_URL: $MODYO_ACCOUNT_URL"
        echo "MODYO_VERSION: $MODYO_VERSION"
        echo "MODYO_TOKEN: $MODYO_TOKEN"
        echo "MODYO_SITE_ID: $MODYO_SITE_ID"
        echo "MODYO_WIDGET_NAME: $MODYO_WIDGET_NAME"
        cd modyo-widgets-investments-accounts 
        yarn modyo-push "$MODYO_WIDGET_NAME"